/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import JDBC.UnidadDeMedidaJDBC;
import POJO.UnidadDeMedidaPOJO;
import javax.swing.JOptionPane;

/**
 *
 * @author cristo
 */
public class PrincipalUnidadDeMedida extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalUnidadDeMedida
     */
    public PrincipalUnidadDeMedida() {
        initComponents();
        cargarTabla();
    }
    
    
    private void cargarTabla() {
        tbControlUnidadDeMedida.setModel(UnidadDeMedidaJDBC.cargarTabla());
    }
    
      private void limpiarComponentes() {
        tfNombre.setText(null);
        taDescripcion.setText(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoAltaControlUnidadDeMedida = new javax.swing.JDialog();
        lbAltaUnidaDeMedida = new javax.swing.JLabel();
        lbnombreAl = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        lbDescripcionAl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        dialogoActualizaControlUnidadDeMedida = new javax.swing.JDialog();
        lbActualizarControlDeMedida = new javax.swing.JLabel();
        lbidAc = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        lbNombreAc = new javax.swing.JLabel();
        tfNombreAc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDescripcionAC = new javax.swing.JTextArea();
        btnGuardarAc = new javax.swing.JButton();
        btnCancelarAc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbControlUnidadDeMedida = new javax.swing.JTable();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        lbAltaUnidaDeMedida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbAltaUnidaDeMedida.setText("ALTA UNIDAD DE MEDIDA");

        lbnombreAl.setText("Nombre ");

        lbDescripcionAl.setText("Descripcion");

        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        jScrollPane2.setViewportView(taDescripcion);

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoAltaControlUnidadDeMedidaLayout = new javax.swing.GroupLayout(dialogoAltaControlUnidadDeMedida.getContentPane());
        dialogoAltaControlUnidadDeMedida.getContentPane().setLayout(dialogoAltaControlUnidadDeMedidaLayout);
        dialogoAltaControlUnidadDeMedidaLayout.setHorizontalGroup(
            dialogoAltaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoAltaControlUnidadDeMedidaLayout.createSequentialGroup()
                .addGroup(dialogoAltaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogoAltaControlUnidadDeMedidaLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(dialogoAltaControlUnidadDeMedidaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dialogoAltaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbDescripcionAl)
                            .addComponent(lbnombreAl))
                        .addGap(29, 29, 29)
                        .addGroup(dialogoAltaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNombre)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoAltaControlUnidadDeMedidaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbAltaUnidaDeMedida)
                .addGap(33, 33, 33))
        );
        dialogoAltaControlUnidadDeMedidaLayout.setVerticalGroup(
            dialogoAltaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAltaControlUnidadDeMedidaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbAltaUnidaDeMedida)
                .addGap(41, 41, 41)
                .addGroup(dialogoAltaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnombreAl)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(dialogoAltaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoAltaControlUnidadDeMedidaLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lbDescripcionAl))
                    .addGroup(dialogoAltaControlUnidadDeMedidaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(dialogoAltaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        lbActualizarControlDeMedida.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbActualizarControlDeMedida.setText("ACTUALIZAR CONTROL UNIDAD DE MEDIDA");

        lbidAc.setText("id");

        tfid.setEditable(false);

        lbNombreAc.setText("Nombre");

        jLabel8.setText("Descripcion");

        taDescripcionAC.setColumns(20);
        taDescripcionAC.setRows(5);
        jScrollPane3.setViewportView(taDescripcionAC);

        btnGuardarAc.setText("GUARDAR");
        btnGuardarAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAcActionPerformed(evt);
            }
        });

        btnCancelarAc.setText("CANCELAR");
        btnCancelarAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoActualizaControlUnidadDeMedidaLayout = new javax.swing.GroupLayout(dialogoActualizaControlUnidadDeMedida.getContentPane());
        dialogoActualizaControlUnidadDeMedida.getContentPane().setLayout(dialogoActualizaControlUnidadDeMedidaLayout);
        dialogoActualizaControlUnidadDeMedidaLayout.setHorizontalGroup(
            dialogoActualizaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbActualizarControlDeMedida)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createSequentialGroup()
                        .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbidAc)
                            .addComponent(lbNombreAc))
                        .addGap(18, 18, 18)
                        .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNombreAc, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoActualizaControlUnidadDeMedidaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarAc)
                .addGap(100, 100, 100)
                .addComponent(btnCancelarAc)
                .addGap(49, 49, 49))
        );
        dialogoActualizaControlUnidadDeMedidaLayout.setVerticalGroup(
            dialogoActualizaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbActualizarControlDeMedida)
                .addGap(40, 40, 40)
                .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbidAc))
                .addGap(18, 18, 18)
                .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombreAc))
                .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(dialogoActualizaControlUnidadDeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarAc)
                    .addComponent(btnGuardarAc))
                .addGap(42, 42, 42))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CONTROL DE UNIDAD DE MEDIDA");

        tbControlUnidadDeMedida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbControlUnidadDeMedida);

        btnAlta.setText("ALTA");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnBaja.setText("BAJA");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnRefresh.setText("REFRESH");

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(btnRegresar)))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefresh)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegresar)
                            .addComponent(btnRefresh)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlta)
                        .addGap(31, 31, 31)
                        .addComponent(btnBaja)
                        .addGap(39, 39, 39)
                        .addComponent(btnActualizar)))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
      
        this.setVisible(false);
        new Menu().setVisible(true);  
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
      //  Object object = new Object(); 
        //abreVentana()
        dialogoAltaControlUnidadDeMedida.setVisible(true);
        dialogoAltaControlUnidadDeMedida.setSize(500, 500);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        int filaSeleccionada = tbControlUnidadDeMedida.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "primero selecciona una fila");
        } else {
            String id = tbControlUnidadDeMedida.getValueAt(filaSeleccionada, 0).toString();
            String nombre = tbControlUnidadDeMedida.getValueAt(filaSeleccionada, 1).toString();
            String descripcion = tbControlUnidadDeMedida.getValueAt(filaSeleccionada, 2).toString();
            tfid.setText(id);
            tfNombreAc.setText(nombre);
            taDescripcionAC.setText(descripcion);
            dialogoActualizaControlUnidadDeMedida.setSize(389, 364);
            dialogoActualizaControlUnidadDeMedida.setLocationRelativeTo(null);
            dialogoActualizaControlUnidadDeMedida.setVisible(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        limpiarComponentes();
        dialogoAltaControlUnidadDeMedida.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelarAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAcActionPerformed

        limpiarComponentes();
        dialogoActualizaControlUnidadDeMedida.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarAcActionPerformed

    private void btnGuardarAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAcActionPerformed

        String id=tfid.getText();
        String nombre = tfNombreAc.getText();
        String descripcion = taDescripcionAC.getText();
       
        UnidadDeMedidaPOJO pojo = new UnidadDeMedidaPOJO();
        pojo.setIdUnidadDeMedida(Integer.parseInt(id));
        pojo.setNombre_unidadDeMedida(nombre);
        pojo.setDescripcion_unidadDeMedida(descripcion);
       
        boolean x = UnidadDeMedidaJDBC.insertar(pojo);
        if (x == true) {
            JOptionPane.showMessageDialog(null, "Éxito");
            limpiarComponentes();
            dialogoActualizaControlUnidadDeMedida.setVisible(false);
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }        

// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarAcActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        String nombre = tfNombre.getText();
        String descripcion = taDescripcion.getText();
       
        UnidadDeMedidaPOJO pojo = new UnidadDeMedidaPOJO();
        pojo.setNombre_unidadDeMedida(nombre);
        pojo.setDescripcion_unidadDeMedida(descripcion);
       
        boolean x = UnidadDeMedidaJDBC.insertar(pojo);
        if (x == true) {
            JOptionPane.showMessageDialog(null, "Éxito");
            cargarTabla();
            limpiarComponentes();
            dialogoAltaControlUnidadDeMedida.setVisible(false);
            
        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }                

// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed

        int filaSeleccionada = tbControlUnidadDeMedida.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "primero selecciona una fila");
        } else {
            String id = tbControlUnidadDeMedida.getValueAt(filaSeleccionada, 0).toString();
            boolean x = UnidadDeMedidaJDBC.eliminar(id);
            if (x == true) {
                JOptionPane.showMessageDialog(null, "exito al eliminar");
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "error al eleminar");
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnBajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUnidadDeMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUnidadDeMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUnidadDeMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUnidadDeMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalUnidadDeMedida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarAc;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarAc;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JDialog dialogoActualizaControlUnidadDeMedida;
    private javax.swing.JDialog dialogoAltaControlUnidadDeMedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbActualizarControlDeMedida;
    private javax.swing.JLabel lbAltaUnidaDeMedida;
    private javax.swing.JLabel lbDescripcionAl;
    private javax.swing.JLabel lbNombreAc;
    private javax.swing.JLabel lbidAc;
    private javax.swing.JLabel lbnombreAl;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextArea taDescripcionAC;
    private javax.swing.JTable tbControlUnidadDeMedida;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNombreAc;
    private javax.swing.JTextField tfid;
    // End of variables declaration//GEN-END:variables
}
