/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import JDBC.PuestoJDBC;
import POJO.PuestoPOJO;
import javax.swing.JOptionPane;

/**
 *
 * @author ADOLFO
 */
public class PrincipalPuesto extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalPuesto
     */
    public PrincipalPuesto() {
        initComponents();
        cargarTabla();
    }
    
        private void cargarTabla(){
            tbPuesto.setModel(PuestoJDBC.cargarTabla());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoAltaPuesto = new javax.swing.JDialog();
        lbAltaPuesto = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        dialogoActualizaPuesto = new javax.swing.JDialog();
        lbNombre1 = new javax.swing.JLabel();
        lbDescripcion1 = new javax.swing.JLabel();
        tfNombre1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btnCancelar1 = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        tfIdPuesto = new javax.swing.JTextField();
        lbControlPuestos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPuesto = new javax.swing.JTable();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        lbAltaPuesto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbAltaPuesto.setText("Alta de Puesto");

        lbNombre.setText("Nombre :");

        lbDescripcion.setText("Descripcion :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoAltaPuestoLayout = new javax.swing.GroupLayout(dialogoAltaPuesto.getContentPane());
        dialogoAltaPuesto.getContentPane().setLayout(dialogoAltaPuestoLayout);
        dialogoAltaPuestoLayout.setHorizontalGroup(
            dialogoAltaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoAltaPuestoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAltaPuesto)
                .addGap(174, 174, 174))
            .addGroup(dialogoAltaPuestoLayout.createSequentialGroup()
                .addGroup(dialogoAltaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoAltaPuestoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(dialogoAltaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbDescripcion)
                            .addComponent(lbNombre))
                        .addGap(31, 31, 31)
                        .addGroup(dialogoAltaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNombre)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))
                    .addGroup(dialogoAltaPuestoLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnCancelar)
                        .addGap(89, 89, 89)
                        .addComponent(btnGuardar)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        dialogoAltaPuestoLayout.setVerticalGroup(
            dialogoAltaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAltaPuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAltaPuesto)
                .addGap(38, 38, 38)
                .addGroup(dialogoAltaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(dialogoAltaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripcion)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(dialogoAltaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addGap(33, 33, 33))
        );

        lbNombre1.setText("Nombre :");

        lbDescripcion1.setText("Descripcion :");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        btnCancelar1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        btnGuardar1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnGuardar1.setText("Guardar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Actualiza Puestos");

        lbID.setText("ID :");

        tfIdPuesto.setEditable(false);

        javax.swing.GroupLayout dialogoActualizaPuestoLayout = new javax.swing.GroupLayout(dialogoActualizaPuesto.getContentPane());
        dialogoActualizaPuesto.getContentPane().setLayout(dialogoActualizaPuestoLayout);
        dialogoActualizaPuestoLayout.setHorizontalGroup(
            dialogoActualizaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoActualizaPuestoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(181, 181, 181))
            .addGroup(dialogoActualizaPuestoLayout.createSequentialGroup()
                .addGroup(dialogoActualizaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialogoActualizaPuestoLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(tfIdPuesto))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialogoActualizaPuestoLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(dialogoActualizaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogoActualizaPuestoLayout.createSequentialGroup()
                                .addGroup(dialogoActualizaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbDescripcion1)
                                    .addComponent(lbNombre1)
                                    .addComponent(lbID))
                                .addGap(31, 31, 31)
                                .addGroup(dialogoActualizaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNombre1)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoActualizaPuestoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCancelar1)
                                .addGap(89, 89, 89)
                                .addComponent(btnGuardar1)
                                .addGap(45, 45, 45)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        dialogoActualizaPuestoLayout.setVerticalGroup(
            dialogoActualizaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoActualizaPuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(dialogoActualizaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(tfIdPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogoActualizaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre1)
                    .addComponent(tfNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(dialogoActualizaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripcion1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(dialogoActualizaPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar1)
                    .addComponent(btnGuardar1))
                .addGap(58, 58, 58))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbControlPuestos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbControlPuestos.setText("Control de Puestos");

        tbPuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbPuesto);

        btnAlta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnBaja.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBaja.setText("Baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegresar.setText("<---- BACK");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbControlPuestos)
                .addGap(229, 229, 229))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBaja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnRegresar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lbControlPuestos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnAlta)
                        .addGap(51, 51, 51)
                        .addComponent(btnBaja)
                        .addGap(49, 49, 49)
                        .addComponent(btnActualizar)
                        .addGap(158, 158, 158)
                        .addComponent(btnRefresh)
                        .addGap(71, 71, 71))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        
        Menu m = new Menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
        
        dialogoAltaPuesto.setLocationRelativeTo(this);
        dialogoAltaPuesto.setSize(497, 318);
        dialogoAltaPuesto.setVisible(true);
        
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        cargarTabla();
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // TODO add your handling code here:
        
        
        int filaSeleccionada = tbPuesto.getSelectedRow();
        
        if (filaSeleccionada==-1) {
            JOptionPane.showMessageDialog(null, "Primero selecciona una fila");
            
        } else {
            String id = tbPuesto.getValueAt(filaSeleccionada, 0) .toString();
            boolean x =PuestoJDBC.eliminar(id);
            
            if (x==true) {
                JOptionPane.showMessageDialog(null, "Exito al Eliminar");
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "Error al Eliminar");
            }
        }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        
        int filaSeleccionada = tbPuesto.getSelectedRow();
        
        if (filaSeleccionada==-1) {
            JOptionPane.showMessageDialog(null, "Primero se debe seleccionar una fila");
        } else {
            String id = tbPuesto.getValueAt(filaSeleccionada, 0).toString();
            String nombre = tbPuesto.getValueAt(filaSeleccionada, 1).toString();
            String descripcion  = tbPuesto.getValueAt(filaSeleccionada, 2).toString();
            
            
            tfIdPuesto.setText(id);
            tfNombre1.setText(nombre);
            jTextArea2.setText(descripcion);
         
                    
            dialogoActualizaPuesto.setSize(527, 388);
            dialogoActualizaPuesto.setLocationRelativeTo(null);
            dialogoActualizaPuesto.setVisible(true);
            
        }
        
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
         //Dialog 1:
        
        
        String nombre = tfNombre.getText();
        String descripcion = jTextArea1.getText();
  

        PuestoPOJO pojo = new PuestoPOJO();

        pojo.setNombre_puesto(nombre);
        pojo.setDescripcion_puesto(descripcion);
 

        boolean x=PuestoJDBC.insertar(pojo);

        if (x) {
            JOptionPane.showMessageDialog(null, "Exito");
            cargarTabla();
            limpiaDialogoAlta();

            dialogoAltaPuesto.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "ERROR... :´v");
        }

        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
        //Dialog  1:
        limpiaDialogoAlta();
        dialogoAltaPuesto.setVisible(false);
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
        
        //Dialog 2:
        
        limpiaDialogoActualizar();
        dialogoActualizaPuesto.setVisible(false);
        
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
        
        //Dialog 2:
        
        String id = tfIdPuesto.getText();
        String nombre = tfNombre1.getText();
        String descripcion = jTextArea2.getText();
       

        PuestoPOJO pojo = new PuestoPOJO();

        pojo.setIdPuesto(Integer.parseInt(id));
        pojo.setNombre_puesto(nombre);
        pojo.setDescripcion_puesto(descripcion);
   

        boolean x = PuestoJDBC.actualizar(pojo);

        if (x==true) {
            JOptionPane.showMessageDialog(null, "Exito Al Actualizar");
            cargarTabla();
            
            dialogoActualizaPuesto.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "Error al Actualizar");
        }


        
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    
        private void limpiaDialogoAlta(){
            tfNombre.setText(null);
            jTextArea1.setText(null);
        }
        
        
        
        private void limpiaDialogoActualizar(){
         tfIdPuesto.setText(null);
         tfNombre1.setText(null);
         jTextArea2.setText(null);
         }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalPuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JDialog dialogoActualizaPuesto;
    private javax.swing.JDialog dialogoAltaPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lbAltaPuesto;
    private javax.swing.JLabel lbControlPuestos;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbDescripcion1;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNombre1;
    private javax.swing.JTable tbPuesto;
    private javax.swing.JTextField tfIdPuesto;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNombre1;
    // End of variables declaration//GEN-END:variables
}
