/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import JDBC.DepartamentoJDBC;
import POJO.DepartamentoPOJO;
import javax.swing.JOptionPane;

/**
 *
 * @author aealc
 */
public class PrincipalDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalDepartamento
     */
    public PrincipalDepartamento() {
        initComponents();
        cargarTabla();
    }

    public void cargarTabla() {
        tbDepartamento.setModel(DepartamentoJDBC.cargarTabla());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoAltaDepartamento = new javax.swing.JDialog();
        lbAltadeDepartamento = new javax.swing.JLabel();
        lbNombreAlta = new javax.swing.JLabel();
        lbDescripcionAlta = new javax.swing.JLabel();
        tfNombreAlta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescripcionAlta = new javax.swing.JTextArea();
        btnGuardarAlta = new javax.swing.JButton();
        btnCancelarAlta = new javax.swing.JButton();
        dialogoActualizaDepartamento = new javax.swing.JDialog();
        lbActualizaDepartamento = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        lbNombreActualiza = new javax.swing.JLabel();
        lbDescripcionActualiza = new javax.swing.JLabel();
        tfIdActualiza = new javax.swing.JTextField();
        tfNombreActualiza = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDescripcionActualiza = new javax.swing.JTextArea();
        btnGuardarActualiza = new javax.swing.JButton();
        btnCancelarActualiza = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDepartamento = new javax.swing.JTable();
        lbControldeDepartamento = new javax.swing.JLabel();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnActualiza = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        lbAltadeDepartamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAltadeDepartamento.setText("Alta de Departamento");

        lbNombreAlta.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbNombreAlta.setText("Nombre: ");

        lbDescripcionAlta.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbDescripcionAlta.setText("Descripcion: ");

        taDescripcionAlta.setColumns(20);
        taDescripcionAlta.setRows(5);
        jScrollPane2.setViewportView(taDescripcionAlta);

        btnGuardarAlta.setText("GUARDAR");
        btnGuardarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAltaActionPerformed(evt);
            }
        });

        btnCancelarAlta.setText("CANCELAR");
        btnCancelarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoAltaDepartamentoLayout = new javax.swing.GroupLayout(dialogoAltaDepartamento.getContentPane());
        dialogoAltaDepartamento.getContentPane().setLayout(dialogoAltaDepartamentoLayout);
        dialogoAltaDepartamentoLayout.setHorizontalGroup(
            dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAltaDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoAltaDepartamentoLayout.createSequentialGroup()
                        .addComponent(lbNombreAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNombreAlta))
                    .addGroup(dialogoAltaDepartamentoLayout.createSequentialGroup()
                        .addComponent(lbAltadeDepartamento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dialogoAltaDepartamentoLayout.createSequentialGroup()
                        .addComponent(lbDescripcionAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogoAltaDepartamentoLayout.createSequentialGroup()
                                .addComponent(btnGuardarAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                                .addComponent(btnCancelarAlta))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        dialogoAltaDepartamentoLayout.setVerticalGroup(
            dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAltaDepartamentoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbAltadeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreAlta)
                    .addComponent(tfNombreAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripcionAlta)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarAlta)
                    .addComponent(btnCancelarAlta))
                .addGap(23, 23, 23))
        );

        lbActualizaDepartamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbActualizaDepartamento.setText("Actualiza Departamento");

        lbId.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbId.setText("ID: ");

        lbNombreActualiza.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbNombreActualiza.setText("Nombre: ");

        lbDescripcionActualiza.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbDescripcionActualiza.setText("Descripcion: ");

        tfIdActualiza.setEditable(false);

        taDescripcionActualiza.setColumns(20);
        taDescripcionActualiza.setRows(5);
        jScrollPane3.setViewportView(taDescripcionActualiza);

        btnGuardarActualiza.setText("GUARDAR");
        btnGuardarActualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActualizaActionPerformed(evt);
            }
        });

        btnCancelarActualiza.setText("CANCELAR");
        btnCancelarActualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActualizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoActualizaDepartamentoLayout = new javax.swing.GroupLayout(dialogoActualizaDepartamento.getContentPane());
        dialogoActualizaDepartamento.getContentPane().setLayout(dialogoActualizaDepartamentoLayout);
        dialogoActualizaDepartamentoLayout.setHorizontalGroup(
            dialogoActualizaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoActualizaDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoActualizaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoActualizaDepartamentoLayout.createSequentialGroup()
                        .addComponent(lbId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIdActualiza))
                    .addGroup(dialogoActualizaDepartamentoLayout.createSequentialGroup()
                        .addComponent(lbNombreActualiza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNombreActualiza))
                    .addGroup(dialogoActualizaDepartamentoLayout.createSequentialGroup()
                        .addComponent(lbActualizaDepartamento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dialogoActualizaDepartamentoLayout.createSequentialGroup()
                        .addComponent(lbDescripcionActualiza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogoActualizaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogoActualizaDepartamentoLayout.createSequentialGroup()
                                .addComponent(btnGuardarActualiza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                                .addComponent(btnCancelarActualiza))
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        dialogoActualizaDepartamentoLayout.setVerticalGroup(
            dialogoActualizaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoActualizaDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbActualizaDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogoActualizaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId)
                    .addComponent(tfIdActualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogoActualizaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreActualiza)
                    .addComponent(tfNombreActualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogoActualizaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripcionActualiza)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(dialogoActualizaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarActualiza)
                    .addComponent(btnCancelarActualiza))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbDepartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDepartamento);

        lbControldeDepartamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbControldeDepartamento.setForeground(new java.awt.Color(255, 0, 0));
        lbControldeDepartamento.setText("CONTROL DE DEPARTAMENTO");

        btnAlta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAlta.setText("ALTA");
        btnAlta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnBaja.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBaja.setText("BAJA");
        btnBaja.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnActualiza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnActualiza.setText("ACTUALIZA");
        btnActualiza.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnActualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaActionPerformed(evt);
            }
        });

        btnRefrescar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRefrescar.setText("REFRESCAR");
        btnRefrescar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegresar.setText("<---  REGRESAR");
        btnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbControldeDepartamento)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAlta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBaja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualiza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefrescar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbControldeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlta)
                        .addGap(18, 18, 18)
                        .addComponent(btnBaja)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualiza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefrescar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed

        dialogoAltaDepartamento.setSize(569, 315);
        dialogoAltaDepartamento.setLocationRelativeTo(null);
        dialogoAltaDepartamento.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed

        int filaSeleccionada = tbDepartamento.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Primero selecciona una fila");

        } else {
            String id = tbDepartamento.getValueAt(filaSeleccionada, 0).toString();
            boolean x = DepartamentoJDBC.eliminar(id);

            if (x == true) {
                JOptionPane.showMessageDialog(null, "Exito al eliminar");
                cargarTabla();

            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar");
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnActualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaActionPerformed

        int filaSeleccionada = tbDepartamento.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Primero selcciona una fila");

        } else {
            String id = tbDepartamento.getValueAt(filaSeleccionada, 0).toString();
            String nombre = tbDepartamento.getValueAt(filaSeleccionada, 1).toString();
            String descripcion = tbDepartamento.getValueAt(filaSeleccionada, 2).toString();

            tfIdActualiza.setText(id);
            tfNombreActualiza.setText(nombre);
            taDescripcionActualiza.setText(descripcion);

            dialogoActualizaDepartamento.setSize(561, 355);
            dialogoActualizaDepartamento.setLocationRelativeTo(null);
            dialogoActualizaDepartamento.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizaActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed

        cargarTabla();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnGuardarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAltaActionPerformed

        String nombre = tfNombreAlta.getText();
        String descripcion = taDescripcionAlta.getText();

        DepartamentoPOJO pojo = new DepartamentoPOJO();

        pojo.setNombre_departamento(nombre);
        pojo.setDescripcion_departamento(descripcion);

        boolean x = DepartamentoJDBC.insertar(pojo);

        if (x == true) {
            JOptionPane.showMessageDialog(null, "Exito");
            cargarTabla();
            limpiaDepartamentolAlta();
            dialogoAltaDepartamento.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarAltaActionPerformed

    private void btnCancelarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAltaActionPerformed

        limpiaDepartamentolAlta();
        dialogoAltaDepartamento.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarAltaActionPerformed

    private void btnGuardarActualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActualizaActionPerformed

        String id = tfIdActualiza.getText();
        String nombre = tfNombreActualiza.getText();
        String descripcion = taDescripcionActualiza.getText();

        DepartamentoPOJO pojo = new DepartamentoPOJO();
        pojo.setIdDepartamento(Integer.parseInt(id));
        pojo.setNombre_departamento(nombre);
        pojo.setDescripcion_departamento(descripcion);

        boolean x = DepartamentoJDBC.actualizar(pojo);

        if (x == true) {
            JOptionPane.showMessageDialog(null, "Exito al actualizar");
            cargarTabla();

            //Hay que hacer limpia dialogo 2 y llamarlo aqui
            dialogoActualizaDepartamento.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "Error al actualizar");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActualizaActionPerformed

    private void btnCancelarActualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActualizaActionPerformed

        limpiaDepartamentolAlta();
        dialogoActualizaDepartamento.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActualizaActionPerformed

    private void limpiaDepartamentolAlta() {
        tfNombreAlta.setText(null);
        taDescripcionAlta.setText(null);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualiza;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnCancelarActualiza;
    private javax.swing.JButton btnCancelarAlta;
    private javax.swing.JButton btnGuardarActualiza;
    private javax.swing.JButton btnGuardarAlta;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JDialog dialogoActualizaDepartamento;
    private javax.swing.JDialog dialogoAltaDepartamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbActualizaDepartamento;
    private javax.swing.JLabel lbAltadeDepartamento;
    private javax.swing.JLabel lbControldeDepartamento;
    private javax.swing.JLabel lbDescripcionActualiza;
    private javax.swing.JLabel lbDescripcionAlta;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbNombreActualiza;
    private javax.swing.JLabel lbNombreAlta;
    private javax.swing.JTextArea taDescripcionActualiza;
    private javax.swing.JTextArea taDescripcionAlta;
    private javax.swing.JTable tbDepartamento;
    private javax.swing.JTextField tfIdActualiza;
    private javax.swing.JTextField tfNombreActualiza;
    private javax.swing.JTextField tfNombreAlta;
    // End of variables declaration//GEN-END:variables
}
