/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author aealc
 */
public class PrincipalDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalDepartamento
     */
    public PrincipalDepartamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoAltaDepartamento = new javax.swing.JDialog();
        lbAltadeDepartamento = new javax.swing.JLabel();
        lbNombreAlta = new javax.swing.JLabel();
        lbDescripcionAlta = new javax.swing.JLabel();
        tfNombreAlta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDepartamentoAlta = new javax.swing.JTextArea();
        btnGuardarAlta = new javax.swing.JButton();
        btnCancelarAlta = new javax.swing.JButton();
        dialogoActualizaDepartamento = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDepartamento = new javax.swing.JTable();
        lbControldeDepartamento = new javax.swing.JLabel();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnActualiza = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        lbAltadeDepartamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAltadeDepartamento.setText("Alta de Departamento");

        lbNombreAlta.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbNombreAlta.setText("Nombre: ");

        lbDescripcionAlta.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbDescripcionAlta.setText("Descripcion: ");

        taDepartamentoAlta.setColumns(20);
        taDepartamentoAlta.setRows(5);
        jScrollPane2.setViewportView(taDepartamentoAlta);

        btnGuardarAlta.setText("GUARDAR");

        btnCancelarAlta.setText("CANCELAR");

        javax.swing.GroupLayout dialogoAltaDepartamentoLayout = new javax.swing.GroupLayout(dialogoAltaDepartamento.getContentPane());
        dialogoAltaDepartamento.getContentPane().setLayout(dialogoAltaDepartamentoLayout);
        dialogoAltaDepartamentoLayout.setHorizontalGroup(
            dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAltaDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoAltaDepartamentoLayout.createSequentialGroup()
                        .addComponent(lbNombreAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNombreAlta))
                    .addGroup(dialogoAltaDepartamentoLayout.createSequentialGroup()
                        .addComponent(lbAltadeDepartamento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dialogoAltaDepartamentoLayout.createSequentialGroup()
                        .addComponent(lbDescripcionAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogoAltaDepartamentoLayout.createSequentialGroup()
                                .addComponent(btnGuardarAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                                .addComponent(btnCancelarAlta))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        dialogoAltaDepartamentoLayout.setVerticalGroup(
            dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAltaDepartamentoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbAltadeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreAlta)
                    .addComponent(tfNombreAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripcionAlta)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(dialogoAltaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarAlta)
                    .addComponent(btnCancelarAlta))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout dialogoActualizaDepartamentoLayout = new javax.swing.GroupLayout(dialogoActualizaDepartamento.getContentPane());
        dialogoActualizaDepartamento.getContentPane().setLayout(dialogoActualizaDepartamentoLayout);
        dialogoActualizaDepartamentoLayout.setHorizontalGroup(
            dialogoActualizaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogoActualizaDepartamentoLayout.setVerticalGroup(
            dialogoActualizaDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbDepartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDepartamento);

        lbControldeDepartamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbControldeDepartamento.setForeground(new java.awt.Color(255, 0, 0));
        lbControldeDepartamento.setText("CONTROL DE DEPARTAMENTO");

        btnAlta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAlta.setText("ALTA");
        btnAlta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBaja.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBaja.setText("BAJA");
        btnBaja.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnActualiza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnActualiza.setText("ACTUALIZA");
        btnActualiza.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnRefrescar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRefrescar.setText("REFRESCAR");
        btnRefrescar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbControldeDepartamento)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualiza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRefrescar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbControldeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlta)
                        .addGap(18, 18, 18)
                        .addComponent(btnBaja)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualiza)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefrescar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualiza;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnCancelarAlta;
    private javax.swing.JButton btnGuardarAlta;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JDialog dialogoActualizaDepartamento;
    private javax.swing.JDialog dialogoAltaDepartamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAltadeDepartamento;
    private javax.swing.JLabel lbControldeDepartamento;
    private javax.swing.JLabel lbDescripcionAlta;
    private javax.swing.JLabel lbNombreAlta;
    private javax.swing.JTextArea taDepartamentoAlta;
    private javax.swing.JTable tbDepartamento;
    private javax.swing.JTextField tfNombreAlta;
    // End of variables declaration//GEN-END:variables
}
